name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-nuget:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal
      
    - name: Publish NuGet packages
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source 'https://api.nuget.org/v3/index.json' --skip-duplicate

  create-github-release:
    needs: build-and-publish-nuget
    runs-on: ubuntu-latest
    
    steps:
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
